import type { Metadata } from 'next'
import Header from './_components/Header'
import './globals.css'

export const metadata: Metadata = {
    title: 'Empresas App',
    description: 'Generated by create next app',
}

export default function RootLayout({ children }: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body suppressHydrationWarning={true}>
                <div className='bg-[#151a28] h-screen'>
                    <div className='rounded-lg'>
                        <Header />
                    </div>
                    <div className='relative rounded-lg overflow-hidden top-20 '>
                        <div className='relative overflow-y-auto py-10 px-5'>
                            {children}
                        </div>
                    </div>
                </div >
            </body>
        </html>
    )
}

